name: wheat_disease_clean
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.2
  easy_localization: ^3.0.3
  pdf: ^3.10.4
  share_plus: ^7.0.0
  path_provider: ^2.1.4
  geocoding: ^2.1.1
  geolocator: ^11.0.0
  image_picker: ^1.1.2
  image: ^4.5.4
  socket_io_client: ^2.0.3+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  intl: ^0.20.2
  tflite_flutter: ^0.10.4
 
  firebase_core: ^2.31.0
  firebase_messaging: ^14.7.10

  
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1

 
  device_info_plus: ^11.1.0


  fluttertoast: ^8.2.4

  
  flutter_markdown: ^0.6.20

  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/translations/en.json
    - assets/translations/hi.json
    - assets/translations/mr.json